export const early = [
  { name: "Defeat 2 dungeon bosses in Weeping Peninsula" },
  { name: "Acquire a +8 non somber weapon" },
  { name: "Defeat 8 Limgrave or Weeping Peninsula bosses" },
  { name: "Wear any part of the Soldier of Godrick armor set" },
  { name: "Parry Margitt 6 times" },
  { name: "Duplicate a remembrance" },
  { name: "Equip 2 different Drake talismans" },
  { name: "Defeat a boss while using a weapon imbued in any type of grease" },
  { name: "Defeat an invader NPC without drinking from any flask" },
  { name: "Acquire the Prince of Death's Pustule" },
  { name: "Acquire any fist type weapon" },
  { name: "Defeat 3 Evergaol bosses" },
  { name: "Acquire the Erdsteel Dagger" },
  { name: "Emote in front of the Two Fingers" },
  { name: "Possess 3 different daggers" },
  { name: "Kill a boss using incantations only" },
  { name: "Acquire a deathroot and give it to Gurranq" },
  { name: "Defeat the Leonine Misbegotten" },
  { name: "Acquire 3 Sacred Tears and 3 Golden Seeds" },
  { name: "Acquire 6 Physick Tears" },
  { name: "Acquire 3 medallion halves" },
  { name: "Pick up a shield type weapon" },
  { name: "Acquire 3 paintings" },
  {
    name: "Suffer from the Poison and Scarlet Rot conditions simultaneously without resting at a site of grace nor dying",
  },
  { name: "Memory of grace with 30k runes" },
];
